### ISSUE TITLE
希望可以添加拖拽排序后的监听事件，返回排序后的list

### ISSUE THREAD

**Issue by protectedMan** [bingoogolapple/BGAPhotoPicker-Android#103]

**Comment by bingoogolapple** [comment]
升级到 v1.2.4

1.升级到 Glide4.x
2.依赖的 bga-adapter 变为 bga-baseadapter
3.九图排序控件增加排序完成回调接口
4.图片选择界面销毁重建保存之前的状态
5.新增系统裁剪图片和从系统相册选择图片

抱歉，这次改动有点大，特别是依赖的 bga-adapter 变为 bga-baseadapter
