### ISSUE TITLE
glide:4.0.0

### ISSUE THREAD

**Issue by Puppy-Love** [bingoogolapple/BGAPhotoPicker-Android#105]
好像不支持 glide 4.0

**Comment by yinhaojun** [comment]
这个库还在维护吗？ 好像8个月了诶，版本也没有进行更新。 反馈说很多手机存在兼容性的问题

**Comment by ITGrocery** [comment]
是的，我也遇到了这个问题。

**Comment by bingoogolapple** [comment]
升级到 v1.2.4

1.升级到 Glide4.x
2.依赖的 bga-adapter 变为 bga-baseadapter
3.九图排序控件增加排序完成回调接口
4.图片选择界面销毁重建保存之前的状态
5.新增系统裁剪图片和从系统相册选择图片

抱歉，这次改动有点大，特别是依赖的 bga-adapter 变为 bga-baseadapter
