### ISSUE TITLE
Glide 4.0的问题

### ISSUE THREAD

**Issue by yuanmenghao** [bingoogolapple/BGAPhotoPicker-Android#116]
你的项目里有的是v4的Glide，很多人项目里都是v3的，glide从3换到4会出一堆问题，项目里用到的地方又太多，不想换，有没有什么解决方案，别让我升级v4的glide，用v3就能正常用。报错代码是 asgif 这段，也没找到在你项目里哪个地方

**Comment by yuanmenghao** [comment]
把加载图片这个步骤开放出来 不就解决了嘛，所有的图片库都是会把glide。load。into这段代码放出来让自定义，不是每个人都喜欢用同一个库

**Comment by yuanmenghao** [comment]
额外加了一个picasso还是解决不了，只要项目里有glide就会强制用glide？

**Comment by bingoogolapple** [comment]
glide4 优先级大于 Picasso 大于 UIL 大于 xUtils

glide4 和 glide3 不兼容，4都出来差不多快一年了

**Comment by yuanmenghao** [comment]
可我的项目都2年了，去改glide4 得好长时间啊，项目里无数个地方用到了。主要是你得把 加载图这个过程放出来 让自己来加载，强制用你的方法总会有不方面的时候。

**Comment by bingoogolapple** [comment]
[兼容Glide3](https://github.com/bingoogolapple/BGAPhotoPicker-Android/issues/118)

**Comment by MyPublicGitHub** [comment]
目前glide4.3.1都兼容不了，把作者的demo  glide版本改成4.3.1也会抱错，请问怎么处理

**Comment by yuanmenghao** [comment]
自己看上面作者发的，自己配置imageloader，不可能报错的

**Comment by huyongqiang** [comment]
后来怎么解决了？ @MyPublicGitHub
