### ISSUE TITLE
在图片选择的时候如果相册中图片太多，BGAPhotoPickerPreviewActivity就崩了

### ISSUE THREAD

**Issue by himi4u** [bingoogolapple/BGAPhotoPicker-Android#122]
![screenshot_20171213-165321](https://user-images.githubusercontent.com/22477512/33930031-84d1acd0-e026-11e7-8b97-36f0f4ab3ec4.png)
“所有图片”中3k多张图片，如果点击一张进行预览，就会出问题，程序直接跳到“添加朋友圈”的界面。
我的其他的相册中有1k多张图片的就没有问题，只有3k多张的“所有图片”点击一张预览会有问题

**Comment by ProerMo** [comment]
同样的问题，请问解决了吗

**Comment by devilsen** [comment]
同求方案。。

**Comment by l455202325** [comment]
这个BUG咋解决啊？

**Comment by mlp1995** [comment]
报的什么错啊 内存溢出吗

**Comment by zjl801** [comment]
同样遇到这个问题

**Comment by chenyabingsuny** [comment]
有解决的这内存溢出的问题吗？

**Comment by chenyabingsuny** [comment]
Second failure launching com.kismartstd.employee/cn.bingoogolapple.photopicker.activity.BGAPhotoPickerPreviewActivity, giving up
    android.os.TransactionTooLargeException: data parcel size 676704 bytes

**Comment by devilsen** [comment]
可以设置一个变量传递，不要直接通过Intent传递，那样是会走Binder的，而Binder是有内存限制的，当大量图片传递时会产生这样的问题。
