### ISSUE TITLE
Caused by: android.os.TransactionTooLargeException: data parcel size xxxxxxx bytes

### ISSUE THREAD

**Issue by shangxiazuoyou** [bingoogolapple/BGAPhotoPicker-Android#134]
当手机内图片数量过多时，比如我的手机内有一万张图片，点击预览时，就会报这个异常，请问有没有什么好的方法来解决这个问题呢？
报错代码如下：
`Intent photoPickerPreviewIntent = new BGAPhotoPickerPreviewActivity.IntentBuilder(this)
                .previewPhotos((ArrayList<String>) mPicAdapter.getData())
                .selectedPhotos(mPicAdapter.getSelectedPhotos())
                .maxChooseCount(mMaxChooseCount)
                .currentPosition(currentPosition)
                .isFromTakePhoto(false)
                .build();
        startActivityForResult(photoPickerPreviewIntent, RC_PREVIEW);`

**Comment by jesse1500** [comment]
同样遇到这个问题

**Comment by zjl801** [comment]
同样遇到这个问题
