### ISSUE TITLE
关于默认蒙层背景颜色

### ISSUE THREAD

**Issue by FreedomCoderELong** [bingoogolapple/BGAPhotoPicker-Android#178]
作者您好，BGASortableNinePhotoLayout.PhotoAdapter的item样式中使用的图片蒙层背景颜色，bga_pp_eighteen_maskColor默认是#CC000000，颜色太深了，能麻烦修改成浅色或透明的吗？

**Comment by KXwonderful** [comment]
颜色是太深了，看上去黑乎乎似的

**Comment by wafer-li** [comment]
@FreedomCoderELong 这个功能的颜色是我写的，临时做了一个，后来看上去太深了。

但是这个颜色你应该是可以在 xml 里面自定义的，用的时候自己定一个浅的就可以了

**Comment by KXwonderful** [comment]
在 colors.xml 中添加下面的代码就变成透明的：
`<color name="bga_pp_eighteen_maskColor">#00000000</color>`
