### ISSUE TITLE
2.02 BGASortableNinePhotoLayout选择的图片和“+”号有黑色的笼罩层

### ISSUE THREAD

**Issue by fanhua1994** [bingoogolapple/BGAPhotoPicker-Android#180]
显示是黑色的。不知道为啥。本地编译demo出来也是。继承到项目也是一样。

**Comment by chenjiancheng** [comment]
我的也是呀，不知道为什么

**Comment by chenjiancheng** [comment]
> 显示是黑色的。不知道为啥。本地编译demo出来也是。继承到项目也是一样。

找到问题了吗？

**Comment by fanhua1994** [comment]
> > 显示是黑色的。不知道为啥。本地编译demo出来也是。继承到项目也是一样。
> 
> 找到问题了吗？

没有啊。不知道为啥

**Comment by chenjiancheng** [comment]
> > > 显示是黑色的。不知道为啥。本地编译demo出来也是。继承到项目也是一样。
> > 
> > 
> > 找到问题了吗？
> 
> 没有啊。不知道为啥

BGAPhotoPicker-Android-master\library\src\main\res\values\bga_pp_colors.xml

<color name="bga_pp_eighteen_maskColor">#CC000000</color>
这个颜色改成透明就行了

**Comment by fanhua1994** [comment]
> > > > 显示是黑色的。不知道为啥。本地编译demo出来也是。继承到项目也是一样。
> > > 
> > > 
> > > 找到问题了吗？
> > 
> > 
> > 没有啊。不知道为啥
> 
> BGAPhotoPicker-Android-master\library\src\main\res\values\bga_pp_colors.xml
> 18 图半透明黑色蒙层
> color name="bga_pp_eighteen_maskColor">#CC000000</color
> 这个颜色改成透明就行了

行。我空了试试！
