### ISSUE TITLE
无响应

### ISSUE THREAD

**Issue by zarvin** [bingoogolapple/BGAPhotoPicker-Android#20]
在低端机型(sony 26ii)上很容易 anr 或者界面要过一阵子才能响应操作，每次卡住的时候，有很多 gc 日志输出，日志输出完成后就能响应界面操作了
> 07-20 16:39:27.275 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13905K/15436K, paused 3ms+3ms, total 25ms
07-20 16:39:27.315 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13905K/15436K, paused 1ms+6ms, total 38ms
07-20 16:39:27.355 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13905K/15436K, paused 3ms+2ms, total 33ms
07-20 16:39:27.385 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 1ms+3ms, total 24ms
07-20 16:39:27.405 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 1ms+3ms, total 24ms
07-20 16:39:27.435 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 2ms+3ms, total 25ms
07-20 16:39:27.475 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13905K/15436K, paused 2ms+4ms, total 37ms
07-20 16:39:27.505 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13905K/15436K, paused 3ms+3ms, total 32ms
07-20 16:39:27.545 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 2ms+4ms, total 36ms
07-20 16:39:27.565 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 1ms+2ms, total 25ms
07-20 16:39:27.595 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 1ms+3ms, total 24ms
07-20 16:39:27.615 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 2ms+3ms, total 24ms
07-20 16:39:27.645 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 2ms+3ms, total 28ms
07-20 16:39:27.675 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 2ms+2ms, total 30ms
07-20 16:39:27.715 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 2ms+2ms, total 37ms
07-20 16:39:27.775 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13905K/15436K, paused 3ms+6ms, total 48ms
07-20 16:39:27.805 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13905K/15436K, paused 3ms+3ms, total 34ms
07-20 16:39:27.835 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 2ms+3ms, total 25ms
07-20 16:39:27.855 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13905K/15436K, paused 1ms+2ms, total 24ms
07-20 16:39:27.885 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 1ms+3ms, total 24ms
07-20 16:39:27.915 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 2ms+4ms, total 34ms
07-20 16:39:27.955 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 3ms+3ms, total 33ms
07-20 16:39:27.975 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 1ms+3ms, total 23ms
07-20 16:39:28.005 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 2ms+3ms, total 24ms
07-20 16:39:28.025 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 2ms+2ms, total 24ms
07-20 16:39:28.055 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 1ms+3ms, total 24ms
07-20 16:39:28.075 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 1ms+3ms, total 23ms
07-20 16:39:28.105 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13906K/15436K, paused 2ms+2ms, total 24ms
07-20 16:39:28.125 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13905K/15436K, paused 2ms+3ms, total 25ms
07-20 16:39:28.155 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13905K/15436K, paused 2ms+3ms, total 25ms
07-20 16:39:28.175 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13905K/15436K, paused 1ms+2ms, total 24ms
07-20 16:39:28.275 26019-26019/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed <1K, 10% free 13905K/15436K, paused 2ms+18ms, total 92ms
07-20 16:39:28.365 26019-26019/cn.bingoogolapple.photopicker.demo I/Choreographer: Skipped 336 frames!  The application may be doing too much work on its main thread.
07-20 16:39:33.715 26019-26039/cn.bingoogolapple.photopicker.demo D/dalvikvm: GC_EXPLICIT freed 8K, 10% free 13905K/15436K, paused 3ms+9ms, total 60ms

**Comment by huangjinhong** [comment]
低端手机确实很卡，CPU占用很高，选完图之后
