### ISSUE TITLE
华为手机图片显示不出来

### ISSUE THREAD

**Issue by lishiyu1810** [bingoogolapple/BGAPhotoPicker-Android#200]
你好,请问能帮忙看一下华为手机图片显示不出来的问题吗?
![5cee374cc059d467751308ee3ebdec2](https://user-images.githubusercontent.com/11992062/110921410-7bf65000-8359-11eb-8992-f332335c52b7.jpg)
![HWFK~G)03B721H24FAF9HY9](https://user-images.githubusercontent.com/11992062/110921445-831d5e00-8359-11eb-9294-eb8878db32bd.png)

**Comment by 751811032** [comment]
这个为什么关掉呢，我也遇到相同的问题

**Comment by lishiyu1810** [comment]
> 这个为什么关掉呢，我也遇到相同的问题
因为targetSdkVersion版本太高的原因  
把target sdk api 设置在29以下就可以了

**Comment by lishiyu1810** [comment]
> 这个为什么关掉呢，我也遇到相同的问题

因为targetSdkVersion版本太高的原因
把target sdk api 设置在29以下就可以了
