### ISSUE TITLE
当项目sdk版本非24的时候引用BGASortableNinePhotoLayout会报错

### ISSUE THREAD

**Issue by Froyo91** [bingoogolapple/BGAPhotoPicker-Android#22]
你好，在使用BGASortableNinePhotoLayout的时候，发现如果项目的compileSdkVersion非24的话，会报如下错误：
android.view.InflateException: Binary XML file line #8: Error inflating class cn.bingoogolapple.photopicker.widget.BGAImageView

**Comment by bingoogolapple** [comment]
@Froyo91 把Demo降到非24的时候会有这个问题吗？

**Comment by caowei922** [comment]
是有这个问题

**Comment by bingoogolapple** [comment]
@Froyo91 我把demo里sdk和v7包都改到23没问题哦

**Comment by bingoogolapple** [comment]
@Froyo91 @caowei922 看下最新版还有没有这个问题

**Comment by Android-zc** [comment]
android.view.InflateException: Binary XML file line #8: Error inflating class cn.bingoogolapple.photopicker.widget.BGAImageView   最新版的如果targetsdk22 也会出现这个错误

**Comment by bingoogolapple** [comment]
升级到 v1.2.4

1.升级到 Glide4.x
2.依赖的 bga-adapter 变为 bga-baseadapter
3.九图排序控件增加排序完成回调接口
4.图片选择界面销毁重建保存之前的状态
5.新增系统裁剪图片和从系统相册选择图片

抱歉，这次改动有点大，特别是依赖的 bga-adapter 变为 bga-baseadapter
