### ISSUE TITLE
使用该项目的demo的时候，发现一些问题

### ISSUE THREAD

**Issue by SmallTony** [bingoogolapple/BGAPhotoPicker-Android#29]
你好，你的这个picker封装的很有水平，不过在使用该项目的demo的时候，发现存在一些问题：
1. 在添加朋友圈界面，初始状态不像微信一样有个+的添加标志，是一片空白，需要点击选择图片才能进入图片选择界面，这样子使用不是很方便。而在选择了图片回到添加朋友圈界面时，那个+的添加标志又出现了，这种体验挺奇怪的。
![image](https://cloud.githubusercontent.com/assets/18010188/18382199/8e6a0078-76b2-11e6-8537-9330afd46013.png)
![image](https://cloud.githubusercontent.com/assets/18010188/18382249/b4cd35b4-76b2-11e6-9683-e0f49f486ed8.png)
2. 在选择玩图片之后，点击图片右上角的删除按钮之后，在所删除的图片还未完全消失之前，如果再次点击该图片，此界面会奔溃，控制台会输出
![image](https://cloud.githubusercontent.com/assets/18010188/18382151/59488dec-76b2-11e6-8b77-6a349897f8c1.png)
这一点需要进行完善。

**Comment by bingoogolapple** [comment]
最新版已 fix 这两个问题
