### ISSUE TITLE
请问第二种效果图怎么设置

### ISSUE THREAD

**Issue by FZJL** [bingoogolapple/BGAPhotoPicker-Android#32]
https://cloud.githubusercontent.com/assets/8949716/18590019/cde4acdc-7c5f-11e6-8877-b702aba7ae0c.png

选择的图片相对第一张要小些

**Comment by bingoogolapple** [comment]
<attr name="bga_snpl_isDeleteDrawableOverlapQuarter" format="boolean"/>

**Comment by FZJL** [comment]
感谢回复，可能是我说的让您误解了，我是看到第二张演示图中那4张被选择的红色图片的尺寸   要比 第一张图中被选择的图片 的尺寸要小，我试了下通过 设置 itemSpanCount 可以实现。还有其他方法吗？
您说的 isDeleteDrawableOverlapQuarter  这个属性 我试了，发现是设置删除图片在被选择图片中的位置。
还有问题是 每次选择图片的时候，都会有个进度圆圈，是不是因为我的图片太多？我发现这个好像是直接查询本机所有的图片

**Comment by bingoogolapple** [comment]
* 每个item的宽度等于屏幕总宽度 / (itemSpanCount + 1)，通过设置itemSpanCount能跳转每个item的宽度。
* 当isDeleteDrawableOverlapQuarter为true时，图片的宽高会缩小DeleteDrawable宽度的一半。
* 本地图片太多时，加载本地图片也会有很大的延时，所以加了加载对话框

**Comment by FZJL** [comment]
请问有没有 一次性清空被选择的图片啊，我看demo里面是发布直接finsh
如果是用 removeItem方法，用下面的来循环
`        for (int i=0;i<ninePhotoLayout.getItemCount();i++){
            ninePhotoLayout.removeItem(i);
        }`
我发现选多张图片的时候，不能清空，还有剩余，貌似是没有同步

**Comment by FZJL** [comment]
private void clearPic() {
        if (ninePhotoLayout.getItemCount()>0){
            ninePhotoLayout.removeItem(0);
            clearPic();
        }
    }

换了递归，貌似没有问题

**Comment by bingoogolapple** [comment]
直接finish不就好了，为什么要这么费劲。

**Comment by FZJL** [comment]
不好意思 又碰到问题了，我做在显示页面的时候，找不到去掉 右上删除图片 的方法，我在布局文件设置
app:bga_snpl_deleteDrawable="@null"  没有用，setDeleteDrawableResId  也不能乱传id吧

在您的demo中 MomentAdapter 里面  并没有找到什么特别的方法，还有这个 setDelegate 这个方法不知道是什么意思，在activity中设置的时候传进个this 我也不知道这个this代表了什么，adapter中this更是报错
