### ISSUE TITLE
删除图片 怎么隐藏啊

### ISSUE THREAD

**Issue by FZJL** [bingoogolapple/BGAPhotoPicker-Android#33]
不好意思 又碰到问题了，我做在显示页面的时候，找不到去掉 右上删除图片 的方法，我在布局文件设置
app:bga_snpl_deleteDrawable="@null" 没有用，setDeleteDrawableResId 也不能乱传id吧

在您的demo中 MomentAdapter 里面 并没有找到什么特别的方法

**Comment by FZJL** [comment]
我 ninePhotoLayout.setDeleteDrawableResId(0);  成功了。。。

**Comment by bingoogolapple** [comment]
你是在做添加界面还是列表界面

**Comment by FZJL** [comment]
列表界面

**Comment by FZJL** [comment]
现在这个ninePhotoLayout 的点击事件貌似有点难搞，就是列表点击图片 放大的效果
我是继承 RecyclerView.Adapter，我应该在 onBindViewHolder 里面怎么处理呢，自定义一个接口把点击事件交给activity处理，这个知道怎么做，是不是要也把 ninePhotoLayout 的点击事件让activity处理啊
holder.ninePhotoLayout.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        onClick.OnItemClick(v,position);
                    }
                });

**Comment by FZJL** [comment]
点击事件是 setDelegate 吧 ，这个参数真不好传啊，在adapter里面不知道传什么，activity里面只能拿到adapter对象，而拿不到holder的 ninePhotoLayout

**Comment by FZJL** [comment]
我在adapter里的 onBindViewHolder  这么写


            if (onClick!=null){
                communityHolder.ninePhotoLayout.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        onClick.OnItemClick(view,position);
                    }
                });

                communityHolder.rl_top.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        onClick.OnItemClick(view,position);
                    }
                });
            }


在activity里面接收事件，但是ninePhotoLayout点了没log啊，rl_top点了倒是有


        adapter.setOnClickListener(new CommunityAdapter.OnClick() {
            @Override
            public void OnItemClick(View view, int position) {
                switch (view.getId()){
                    case R.id.show_pic:
                        Logger.e("touch nine");
                        break;
                    case R.id.rl_top:
                        Logger.e("touch rl_top");
                        break;
                }
            }

            @Override
            public void OnItemLongClick(View view, int position) {

            }
        });

**Comment by FZJL** [comment]
现在主要的问题的是   ninePhotoLayout 的setDelegate  在哪里设置
我在构造adapter的时候 把context activity都带过来了，init可以，但是setDelegate  就真不知道如何搞了



class CommunityHolder extends RecyclerView.ViewHolder{
        @Bind(R.id.iv_user)
        ImageView iv_user;

        @Bind(R.id.tv_username)
        TextView tv_username;

        @Bind(R.id.tv_time)
        TextView tv_time;

        @Bind(R.id.tv_location)
        TextView tv_location;

        @Bind(R.id.tv_content)
        TextView tv_content;

        @Bind(R.id.rl_top)
        RelativeLayout rl_top;

        @Bind(R.id.show_pic)
        BGASortableNinePhotoLayout ninePhotoLayout;

        public CommunityHolder(View itemView) {
            super(itemView);
            ButterKnife.bind(this,itemView);
            ninePhotoLayout.setIsPlusSwitchOpened(false);
            ninePhotoLayout.setIsSortable(false);
            ninePhotoLayout.setDeleteDrawableResId(0);
            ninePhotoLayout.init(activity);
        }
    }

**Comment by FZJL** [comment]
我把选择图片的布局 BGASortableNinePhotoLayout   直接复制过来用了，列表显示的时候应该是 用BGANinePhotoLayout

但是依然不知道 在哪怎么 setDelegate     就这最后一步了

**Comment by FZJL** [comment]
我靠  我也是服了我自己了
我在activity里面
BGANinePhotoLayout.Delegate delegate = CommunityActivity.this;
构造adapter的时候 把这个delegate 带进去，然后在 holder里面 
ninePhotoLayout.setDelegate(delegate);
不需要在 adapter里面自己实现的方法里面做点击事件的处理了

**Comment by bingoogolapple** [comment]
麻烦你下次先把 Demo 看明白再搞啊

**Comment by FZJL** [comment]
哈哈，不好意思，新手，现在有个问题是这样上传的图片都没有压缩，照片都是2-3MB，我对怎么压缩也没有了解，您是怎么处理的呢

**Comment by bingoogolapple** [comment]
这种问题你应该先查文档和Google，别一遇到问题就问

**Comment by FZJL** [comment]
哈哈，就是平时都是靠自己查，这次您热心回答，搞我就想一次问到底了
