### ISSUE TITLE
图片选择不能自适应屏幕大小

### ISSUE THREAD

**Issue by douya40** [bingoogolapple/BGAPhotoPicker-Android#35]
图片选择返回的图片布局不能自适应屏幕大小

**Comment by bingoogolapple** [comment]
麻再描述详细点

**Comment by imexception** [comment]
感觉给个初始宽度，自动换行更好，跟流式布局那样，你这种适应性确实不是太好

**Comment by bingoogolapple** [comment]
看最新版的 demo 和 https://github.com/bingoogolapple/BGAPhotoPicker-Android/blob/master/library/src/main/res/values/bga_pp_attrs.xml
