### ISSUE TITLE
怎么自定义九宫格

### ISSUE THREAD

**Issue by rmtic** [bingoogolapple/BGAPhotoPicker-Android#37]
1.比如现在是图片+加删除的按钮，我想改成图片+文字+删除按钮

**Comment by bingoogolapple** [comment]
自己改 https://github.com/bingoogolapple/BGAPhotoPicker-Android/blob/master/library/src/main/java/cn/bingoogolapple/photopicker/widget/BGASortableNinePhotoLayout.java 的源码
