### ISSUE TITLE
希望不忙的话解决下BGASortableNinePhotoLayout设置match_parent无效的问题

### ISSUE THREAD

**Issue by MoneyNotFoundException** [bingoogolapple/BGAPhotoPicker-Android#46]
BGASortableNinePhotoLayout跟BGANinePhotoLayout设置match_parent无效，不能充满父类容器，昨天试着改了下，因本人能力有限，还是没能解决这个问题，还望大神抽空处理下这个问题。

**Comment by bingoogolapple** [comment]
用 v1.1.8
