### ISSUE TITLE
关于需求

### ISSUE THREAD

**Issue by happinesspeople** [bingoogolapple/BGAPhotoPicker-Android#53]
可不可以将拍照跟相册分开呀？也就是在外部可以点击拍照，然后图片就添加上去，这是点击相册还能够同步选中刚刚拍的照片？

**Comment by bingoogolapple** [comment]
现在能实现你说的那种效果啊，你可以好好研究下 demo 和 https://github.com/bingoogolapple/BGAPhotoPicker-Android/blob/master/library/src/main/java/cn/bingoogolapple/photopicker/util/BGAImageCaptureManager.java

BGAImageCaptureManager 可以单独集成到你自己的 activity 里处理拍照和裁剪

**Comment by happinesspeople** [comment]
嗯嗯 已经实现了单独集成了，谢谢------------------------------------------------------------------发件人：王浩 <notifications@github.com>发送时间：2017年1月11日(星期三) 00:18收件人：bingoogolapple/BGAPhotoPicker-Android <BGAPhotoPicker-Android@noreply.github.com>抄　送：陈衍权 <lion@hengha.ren>; Author <author@noreply.github.com>主　题：Re: [bingoogolapple/BGAPhotoPicker-Android] 关于需求 (#53)
现在能实现你说的那种效果啊，你可以好好研究下 demo 和 https://github.com/bingoogolapple/BGAPhotoPicker-Android/blob/master/library/src/main/java/cn/bingoogolapple/photopicker/util/BGAImageCaptureManager.javaBGAImageCaptureManager 可以单独集成到你自己的 activity 里处理拍照和裁剪—
