### ISSUE TITLE
Fragment里面不能用？

### ISSUE THREAD

**Issue by ThreadDeath** [bingoogolapple/BGAPhotoPicker-Android#66]
首先感谢大神的一系列的开源项目。我在fragment里面用，为啥设置了mPhotosSnpl.setDelegate(this);但是断点看这个delegate在点击添加图片的时候总是空，何解？

**Comment by sunyz2016** [comment]
ThreadDeath 同学 我也遇到了 请问你解决吗？谢谢回复

**Comment by bingoogolapple** [comment]
自己看 api 看 demo

**Comment by dashifuguye** [comment]
新手，麻烦大神指导下如何在fragment中使用 @bingoogolapple

**Comment by dashifuguye** [comment]
解决拉，谢谢
