### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by SmallTony** [bingoogolapple/BGAPhotoPicker-Android#75]
这个图片选择器写的真的是太好了，如果能再加上一个图片编辑的功能（比如说图片裁剪，涂鸦）就更好了。希望大神有空的时候能够在选择图片的时候加上这个功能。那就更完美了！

**Comment by bingoogolapple** [comment]
升级到最新版试试

1.升级到 Glide4.x
2.依赖的 bga-adapter 变为 bga-baseadapter
3.九图排序控件增加排序完成回调接口
4.图片选择界面销毁重建保存之前的状态
5.新增系统裁剪图片和从系统相册选择图片

抱歉，这次改动有点大，特别是依赖的 bga-adapter 变为 bga-baseadapter
