### ISSUE TITLE
类型转化异常

### ISSUE THREAD

**Issue by wjehovah** [bingoogolapple/BGAPhotoPicker-Android#76]
<img width="770" alt="2017-01-06 2 12 50" src="https://cloud.githubusercontent.com/assets/5822929/21709207/462b4b44-d41a-11e6-999f-03f161d7b4e5.png">

**Comment by bingoogolapple** [comment]
你用的哪个版本？

**Comment by wjehovah** [comment]
最新的。

**Comment by bingoogolapple** [comment]
不要说最新的，要说具体版本号。类型转换异常这个问题在 1.2.2 里已经修复了的

现在最新的是 1.2.2，你确定你用的是 1.2.2 ？

还有就是手机型号、系统版本也说一下

**Comment by wjehovah** [comment]
谢谢，这么快反应。确定 是1.2.2 
设备机型

荣耀 H60-L01
系统版本

Android 4.4.2,level 19
ROM

HuaWei/EMOTION
CPU架构

armeabi-v7a

暂时没有发现其他机型有问题

**Comment by bingoogolapple** [comment]
我在 华为 C8818 Android 4.4.4 API 19 上跑也没问题

确定一下报这个错时集成的 bga-photopicker 版本是都少？
会不会收集到这个崩溃日志的 app 版本集成的不是 bga-photopicker 1.2.2 版？

**Comment by bingoogolapple** [comment]
搞定了吗？

**Comment by wjehovah** [comment]
不好意思，最近几天没有报异常了。看日期 bug应该不是1.2.2版，1.2.2版没有此问题。
感谢作者的一系列开源库
