### ISSUE TITLE
图片选择时出现的bug

### ISSUE THREAD

**Issue by happinesspeople** [bingoogolapple/BGAPhotoPicker-Android#79]
我使用的是魅蓝note3，android版本是5.1的，运行你最新的demo的时候，在
![image](https://cloud.githubusercontent.com/assets/23250466/22054020/b4eb8e90-dd8e-11e6-808f-154b14e178a4.png)
，很多图片都没有显示出来，我看了一下，那些都是拍照的照片，比较大。

然后还想问一下作者一个问题，我之前很早的时候就集成了你的库，我是通过module方式集成的，之前你的library就只有cn/bingoogolapple/photopicker这一个包，现在多出来了一个uk/co/senab/photoview这个包。所以想知道一下，你这个新添加的包是不是只是用于图片显示，我不去导入是不是应该也没问题呢？

**Comment by happinesspeople** [comment]
只要是拍照的照片都显示不了

**Comment by bingoogolapple** [comment]
升级到最新版试试

1.升级到 Glide4.x
2.依赖的 bga-adapter 变为 bga-baseadapter
3.九图排序控件增加排序完成回调接口
4.图片选择界面销毁重建保存之前的状态
5.新增系统裁剪图片和从系统相册选择图片

抱歉，这次改动有点大，特别是依赖的 bga-adapter 变为 bga-baseadapter
