### ISSUE TITLE
删除选择图片背景错位

### ISSUE THREAD

**Issue by suojiang** [bingoogolapple/BGAPhotoPicker-Android#81]
运行demo，从图片库里选择两张图片，然后将第二张和第一张调换位置（或者第一张与第二张调换位置），再依次删除图片，“+”选择图片背景就和之前选择图片重叠了。希望有空解决一下，多谢！

**Comment by A171811440** [comment]
1.只能使用线上的lib，不能加载本地lib
2.使用线上lib的时候，点击图片预览直接崩溃。

**Comment by bingoogolapple** [comment]
升级到最新版试试

1.升级到 Glide4.x
2.依赖的 bga-adapter 变为 bga-baseadapter
3.九图排序控件增加排序完成回调接口
4.图片选择界面销毁重建保存之前的状态
5.新增系统裁剪图片和从系统相册选择图片

抱歉，这次改动有点大，特别是依赖的 bga-adapter 变为 bga-baseadapter

**Comment by kyriej** [comment]
确实有这问题，请问楼主解决了吗，我用的是最新的版
