### ISSUE TITLE
线上和本地lib的问题

### ISSUE THREAD

**Issue by A171811440** [bingoogolapple/BGAPhotoPicker-Android#82]
1.只能使用线上的lib，不能加载本地lib

**Comment by bingoogolapple** [comment]
什么意思？

升级到最新版试试

1.升级到 Glide4.x
2.依赖的 bga-adapter 变为 bga-baseadapter
3.九图排序控件增加排序完成回调接口
4.图片选择界面销毁重建保存之前的状态
5.新增系统裁剪图片和从系统相册选择图片

抱歉，这次改动有点大，特别是依赖的 bga-adapter 变为 bga-baseadapter
