### ISSUE TITLE
拍照后图片预览无法去掉

### ISSUE THREAD

**Issue by 921668753** [bingoogolapple/BGAPhotoPicker-Android#84]

**Comment by bingoogolapple** [comment]
升级到最新版试试，直接 BGAPhotoHelpe 调用系统相机拍照，参考 https://github.com/bingoogolapple/BGAPhotoPicker-Android/blob/master/demo/src/main/java/cn/bingoogolapple/photopicker/demo/activity/SystemGalleryActivity.java

1.升级到 Glide4.x
2.依赖的 bga-adapter 变为 bga-baseadapter
3.九图排序控件增加排序完成回调接口
4.图片选择界面销毁重建保存之前的状态
5.新增系统裁剪图片和从系统相册选择图片

抱歉，这次改动有点大，特别是依赖的 bga-adapter 变为 bga-baseadapter
