### ISSUE TITLE
希望增加繁体、英文语言

### ISSUE THREAD

**Issue by yinhaojun** [bingoogolapple/BGAPhotoPicker-Android#87]
希望增加繁体、英文语言

**Comment by bingoogolapple** [comment]
求 PR

<resources>
    <string name="bga_pp_take_picture">拍摄照片</string>
    <string name="bga_pp_not_support_take_photo">当前设备不支持拍照</string>
    <string name="bga_pp_not_support_crop">当前设备不支持裁剪图片</string>
    <string name="bga_pp_toast_photo_picker_max">最多只能选择 %1$d 张图片</string>
    <string name="bga_pp_all_image">所有图片</string>
    <string name="bga_pp_confirm">确定</string>
    <string name="bga_pp_choose">选择</string>
    <string name="bga_pp_view_photo">查看图片</string>
    <string name="bga_pp_download_img_failure">下载到图片失败</string>
    <string name="bga_pp_save_img_failure">保存图片失败，再试试?</string>
    <string name="bga_pp_save_img_success_folder">图片已保存至 %s 文件夹</string>
</resources>

**Comment by jcsunran** [comment]
有一些添加多语言版本并未生效，比如  bga_pp_confirm  bga_pp_choose，  无论切换什么语言，都显示中文版。
