### ISSUE TITLE
targetSdkVersion 22 运行会崩溃

### ISSUE THREAD

**Issue by chendd** [bingoogolapple/BGAPhotoPicker-Android#91]
cn.bingoogolapple.photopicker.activity.BGAPhotoPreviewActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class android.support.v7.widget.ViewStubCompat 有没好的解决办法

**Comment by bingoogolapple** [comment]
升到最新版吧

升级到 v1.2.4

1.升级到 Glide4.x
2.依赖的 bga-adapter 变为 bga-baseadapter
3.九图排序控件增加排序完成回调接口
4.图片选择界面销毁重建保存之前的状态
5.新增系统裁剪图片和从系统相册选择图片

抱歉，这次改动有点大，特别是依赖的 bga-adapter 变为 bga-baseadapter
