### ISSUE TITLE
能否直接调取拍照？不显示图片的列表？

### ISSUE THREAD

**Issue by baowenqing** [bingoogolapple/BGAPhotoPicker-Android#92]
点击添加图片，启动拍照（不显示图片列表），后面的逻辑都不变

**Comment by bingoogolapple** [comment]
参考 https://github.com/bingoogolapple/BGAPhotoPicker-Android/blob/master/demo/src/main/java/cn/bingoogolapple/photopicker/demo/activity/SystemGalleryActivity.java

升级到 v1.2.4

1.升级到 Glide4.x
2.依赖的 bga-adapter 变为 bga-baseadapter
3.九图排序控件增加排序完成回调接口
4.图片选择界面销毁重建保存之前的状态
5.新增系统裁剪图片和从系统相册选择图片

抱歉，这次改动有点大，特别是依赖的 bga-adapter 变为 bga-baseadapter
