### ISSUE TITLE
问下能加载网络图片吗

### ISSUE THREAD

**Issue by qaz349293703** [bingoogolapple/BGAPhotoPicker-Android#94]
比如需求是我先把本地的图片添加到九宫格上传到某个订单，。后面我再进去查看这个订单。因为可以进行内容编辑，比如我重新更换了这个订单下的图片。所以要先加载我上次上传的图片。。。。。

**Comment by qaz349293703** [comment]
已经解决

**Comment by xiaobaidian** [comment]
想问下您是怎么解决的？？？

**Comment by cs8** [comment]
ArrayList<String> photosss =new ArrayList<>();
        photosss.add("");
        mPhotosSnpl.setData(photosss);
        mPhotosSnpl.setEditable(false/true);
